version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers
    - image: circleci/postgres
      environment:
      - POSTGRES_PASSWORD: 'postgres'

    working_directory: ~/rails-blog

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          gem install bundler -v 2.0.2
          bundle install --jobs=4 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Database setup
    - run: mv ./config/database.yml.ci ./config/database.yml

    # Database setup
    - run:
        name: Databasesetup
        command: |
           yarn install --check-files
           bundle exec rails db:create RAILS_ENV=development
           bundle exec rails db:schema:load
